// Mesh swarm implementation using libp2p with Circuit Relay v2 and DCUTR

use libp2p::{
    dcutr, identify, noise, relay,
    swarm::{NetworkBehaviour, Swarm, SwarmEvent},
    tcp, yamux, Multiaddr, PeerId, SwarmBuilder,
};
use std::collections::VecDeque;
use std::time::Duration;
use tracing::{debug, info, instrument, warn};

use super::events::{ConnectionInfo, ConnectionType, MeshEvent};
use crate::api::types::PeerPunchPlan;
use crate::connectivity::{
    load_runtime_connectivity_state, persist_observed_reachability_addr,
    persist_runtime_connectivity_state, select_direct_dial_multiaddrs, ConnectivityPath,
    ConnectivityStatus, DeviceConnectivityState,
};
use crate::errors::{AgentError, Result};

/// Composed network behaviour for the mesh agent
#[derive(NetworkBehaviour)]
#[behaviour(to_swarm = "MeshBehaviourEvent")]
pub struct MeshBehaviour {
    pub identify: identify::Behaviour,
    pub relay_client: relay::client::Behaviour,
    pub dcutr: dcutr::Behaviour,
}

/// Events generated by MeshBehaviour
#[derive(Debug)]
pub enum MeshBehaviourEvent {
    Identify(Box<identify::Event>),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
}

impl From<identify::Event> for MeshBehaviourEvent {
    fn from(event: identify::Event) -> Self {
        MeshBehaviourEvent::Identify(Box::new(event))
    }
}

impl From<relay::client::Event> for MeshBehaviourEvent {
    fn from(event: relay::client::Event) -> Self {
        MeshBehaviourEvent::RelayClient(event)
    }
}

impl From<dcutr::Event> for MeshBehaviourEvent {
    fn from(event: dcutr::Event) -> Self {
        MeshBehaviourEvent::Dcutr(event)
    }
}

/// Configuration for the mesh swarm
#[derive(Debug, Clone)]
pub struct MeshSwarmConfig {
    /// Relay server multiaddress
    pub relay_addr: Multiaddr,

    /// Keep-alive interval for idle connections
    pub keep_alive: Duration,
}

impl Default for MeshSwarmConfig {
    fn default() -> Self {
        Self {
            relay_addr: std::env::var("MESHNET_RELAY_ADDR")
                .ok()
                .and_then(|addr| addr.parse().ok())
                .unwrap_or_else(|| {
                    "/dns4/relay.meshnet.invalid/tcp/4001"
                        .parse()
                        .expect("static default relay address must be valid")
                }),
            keep_alive: Duration::from_secs(60),
        }
    }
}

/// Builder for creating a mesh swarm
pub struct MeshSwarmBuilder {
    keypair: libp2p::identity::Keypair,
    config: MeshSwarmConfig,
}

impl MeshSwarmBuilder {
    /// Create a new builder with the given keypair
    pub fn new(keypair: libp2p::identity::Keypair) -> Self {
        Self {
            keypair,
            config: MeshSwarmConfig::default(),
        }
    }

    /// Set the relay server address
    pub fn with_relay_addr(mut self, addr: Multiaddr) -> Self {
        self.config.relay_addr = addr;
        self
    }

    /// Set the keep-alive duration
    pub fn with_keep_alive(mut self, duration: Duration) -> Self {
        self.config.keep_alive = duration;
        self
    }

    /// Build the mesh swarm
    #[instrument(skip(self), fields(peer_id = %self.keypair.public().to_peer_id()))]
    pub fn build(self) -> Result<MeshSwarm> {
        info!("Building mesh swarm");

        let swarm = SwarmBuilder::with_existing_identity(self.keypair)
            .with_tokio()
            // TCP transport with Noise encryption and Yamux multiplexing
            .with_tcp(
                tcp::Config::default(),
                noise::Config::new,
                yamux::Config::default,
            )
            .map_err(|e| AgentError::Network(format!("Failed to configure TCP: {}", e)))?
            // QUIC transport (has built-in encryption)
            .with_quic()
            .with_relay_client(noise::Config::new, yamux::Config::default)
            .map_err(|e| AgentError::Network(format!("Failed to configure relay client: {}", e)))?
            .with_behaviour(|keypair, relay_client| {
                // Identify protocol
                let identify = identify::Behaviour::new(
                    identify::Config::new("/mesh/1.0.0".to_string(), keypair.public())
                        .with_agent_version(format!("mesh-agent/{}", env!("CARGO_PKG_VERSION"))),
                );

                // DCUTR for hole-punching and direct connections
                let dcutr = dcutr::Behaviour::new(keypair.public().to_peer_id());

                Ok(MeshBehaviour {
                    identify,
                    relay_client,
                    dcutr,
                })
            })
            .map_err(|e| AgentError::Network(format!("Failed to build behaviour: {:?}", e)))?
            .with_swarm_config(|c| c.with_idle_connection_timeout(self.config.keep_alive))
            .build();

        info!("Mesh swarm created successfully");

        Ok(MeshSwarm {
            swarm,
            config: self.config,
            relay_peer_id: None,
            ring_connections: None,
            pending_events: VecDeque::new(),
        })
    }
}

/// Ring neighbor connections for all-reduce communication
#[derive(Debug, Clone)]
pub struct RingConnections {
    /// Left neighbor in the ring (we receive from this peer)
    pub left_peer: PeerId,
    /// Right neighbor in the ring (we send to this peer)
    pub right_peer: PeerId,
}

/// Main mesh swarm struct
pub struct MeshSwarm {
    swarm: Swarm<MeshBehaviour>,
    config: MeshSwarmConfig,
    relay_peer_id: Option<PeerId>,
    ring_connections: Option<RingConnections>,
    pending_events: VecDeque<MeshEvent>,
}

impl MeshSwarm {
    fn relay_endpoint_matches(&self, remote_addr: &Multiaddr) -> bool {
        relay_base_addr(remote_addr) == relay_base_addr(&self.config.relay_addr)
    }

    /// Create a new builder for constructing a mesh swarm
    pub fn builder(keypair: libp2p::identity::Keypair) -> MeshSwarmBuilder {
        MeshSwarmBuilder::new(keypair)
    }

    /// Get the local peer ID
    pub fn local_peer_id(&self) -> &PeerId {
        self.swarm.local_peer_id()
    }

    /// Connect to the relay server
    #[instrument(skip(self), fields(peer_id = %self.local_peer_id(), relay = %self.config.relay_addr))]
    pub fn connect_to_relay(&mut self) -> Result<()> {
        info!("Dialing relay server");
        self.swarm.dial(self.config.relay_addr.clone())?;
        Ok(())
    }

    /// Listen on default direct transports for inbound peer connections.
    pub fn listen_on_direct_addrs(&mut self) -> Result<()> {
        self.swarm.listen_on(
            "/ip4/0.0.0.0/tcp/0"
                .parse()
                .expect("static tcp addr must parse"),
        )?;
        self.swarm.listen_on(
            "/ip4/0.0.0.0/udp/0/quic-v1"
                .parse()
                .expect("static quic addr must parse"),
        )?;
        Ok(())
    }

    /// Listen on the relay server (create a reservation)
    #[instrument(skip(self), fields(peer_id = %self.local_peer_id(), relay = %relay_peer_id))]
    pub fn listen_on_relay(&mut self, relay_peer_id: PeerId) -> Result<()> {
        info!("Creating relay reservation");

        // Listen on relay with p2p-circuit protocol
        self.swarm.listen_on(
            self.config
                .relay_addr
                .clone()
                .with(libp2p::multiaddr::Protocol::P2p(relay_peer_id))
                .with(libp2p::multiaddr::Protocol::P2pCircuit),
        )?;

        self.relay_peer_id = Some(relay_peer_id);
        Ok(())
    }

    /// Dial a peer through the relay
    #[instrument(skip(self), fields(local = %self.local_peer_id(), target = %peer_id))]
    pub fn dial_peer(&mut self, peer_id: PeerId) -> Result<()> {
        let relay_peer_id = self
            .relay_peer_id
            .ok_or_else(|| AgentError::Network("Not connected to relay server".to_string()))?;

        info!("Dialing peer through relay");

        // Construct relay circuit address: /ip4/.../tcp/.../p2p/<relay>/p2p-circuit/p2p/<target>
        let relay_addr = self
            .config
            .relay_addr
            .clone()
            .with(libp2p::multiaddr::Protocol::P2p(relay_peer_id))
            .with(libp2p::multiaddr::Protocol::P2pCircuit)
            .with(libp2p::multiaddr::Protocol::P2p(peer_id));

        debug!("Relay circuit address: {}", relay_addr);
        self.swarm.dial(relay_addr)?;
        Ok(())
    }

    pub fn dial_direct_peer(&mut self, peer_id: PeerId, addrs: &[Multiaddr]) -> Result<()> {
        let ranked_addrs = select_direct_dial_multiaddrs(peer_id, addrs);
        let mut dialed = false;
        for dial_addr in ranked_addrs {
            match self.swarm.dial(dial_addr.clone()) {
                Ok(()) => {
                    dialed = true;
                    debug!(peer_id = %peer_id, addr = %dial_addr, "Dialing peer directly");
                }
                Err(e) => {
                    warn!(peer_id = %peer_id, addr = %dial_addr, error = %e, "Direct dial attempt failed");
                }
            }
        }

        if dialed {
            Ok(())
        } else {
            Err(AgentError::Network(format!(
                "Failed to dial peer {} on any advertised direct address",
                peer_id
            )))
        }
    }

    pub fn dial_direct_peer_with_punch_plan(
        &mut self,
        peer_id: PeerId,
        plan: &PeerPunchPlan,
    ) -> Result<()> {
        let planned_addrs = select_direct_dial_multiaddrs(
            peer_id,
            &plan
                .target_candidates
                .iter()
                .filter_map(|candidate| candidate.endpoint.parse().ok())
                .collect::<Vec<Multiaddr>>(),
        );
        if planned_addrs.is_empty() {
            return Err(AgentError::Network(format!(
                "Punch plan for peer {} has no viable direct candidates",
                peer_id
            )));
        }

        self.pending_events
            .push_back(MeshEvent::PunchPathAttemptInitiated {
                peer_id,
                reason: format!("{:?}", plan.reason),
                candidate_count: plan.target_candidates.len(),
                relay_rendezvous_required: plan.relay_rendezvous_required,
            });
        self.dial_direct_peer(peer_id, &planned_addrs)
    }

    fn dial_neighbor(
        &mut self,
        peer_id: PeerId,
        addrs: &[Multiaddr],
        plan: Option<&PeerPunchPlan>,
    ) {
        let direct_result = match plan {
            Some(plan) => self.dial_direct_peer_with_punch_plan(peer_id, plan),
            None => self.dial_direct_peer(peer_id, addrs),
        };

        match direct_result {
            Ok(()) => {}
            Err(direct_error) => {
                warn!(
                    peer_id = %peer_id,
                    error = %direct_error,
                    "Direct dial failed for neighbor"
                );
            }
        }
    }

    /// Poll the swarm for the next event
    pub async fn next_event(&mut self) -> Option<MeshEvent> {
        use futures::StreamExt;

        loop {
            if let Some(event) = self.pending_events.pop_front() {
                return Some(event);
            }

            match self.swarm.next().await? {
                // Identify events
                SwarmEvent::Behaviour(MeshBehaviourEvent::Identify(event)) => match *event {
                    identify::Event::Received { peer_id, info, .. } => {
                        debug!(
                            peer_id = %peer_id,
                            protocol = %info.protocol_version,
                            agent = %info.agent_version,
                            "Peer identified"
                        );
                        return Some(MeshEvent::PeerIdentified {
                            peer_id,
                            protocol_version: info.protocol_version,
                            agent_version: info.agent_version,
                        });
                    }
                    identify::Event::Sent { .. } => {
                        debug!("Sent identify info");
                    }
                    identify::Event::Pushed { .. } => {
                        debug!("Pushed identify info");
                    }
                    identify::Event::Error { peer_id, error, .. } => {
                        warn!(peer_id = %peer_id, error = %error, "Identify error");
                    }
                },

                // Relay client events
                SwarmEvent::Behaviour(MeshBehaviourEvent::RelayClient(event)) => {
                    use relay::client::Event;
                    match event {
                        Event::ReservationReqAccepted {
                            relay_peer_id,
                            renewal,
                            limit,
                        } => {
                            if renewal {
                                info!(relay = %relay_peer_id, "Relay reservation renewed");
                            } else {
                                info!(relay = %relay_peer_id, limit = ?limit, "Relay reservation accepted");
                            }
                            let should_mark_relay = !matches!(
                                load_runtime_connectivity_state(),
                                Some(DeviceConnectivityState {
                                    active_path: ConnectivityPath::Direct,
                                    status: ConnectivityStatus::Connected,
                                    ..
                                })
                            );
                            if should_mark_relay {
                                let _ =
                                    persist_runtime_connectivity_state(&DeviceConnectivityState {
                                        active_path: ConnectivityPath::Relayed,
                                        active_endpoint: Some(self.config.relay_addr.to_string()),
                                        status: ConnectivityStatus::Connected,
                                    });
                            }
                            return Some(MeshEvent::ReservationAccepted {
                                relay_peer_id,
                                renewal_timeout: Duration::from_secs(30),
                            });
                        }
                        Event::OutboundCircuitEstablished {
                            relay_peer_id,
                            limit,
                        } => {
                            debug!(relay = %relay_peer_id, limit = ?limit, "Outbound circuit established");
                        }
                        Event::InboundCircuitEstablished { src_peer_id, limit } => {
                            debug!(src = %src_peer_id, limit = ?limit, "Inbound circuit established");
                        }
                    }
                }

                // DCUTR events
                SwarmEvent::Behaviour(MeshBehaviourEvent::Dcutr(event)) => match event.result {
                    Ok(_) => {
                        info!(peer_id = %event.remote_peer_id, "Direct connection upgrade succeeded");
                        let _ = persist_runtime_connectivity_state(&DeviceConnectivityState {
                            active_path: ConnectivityPath::Direct,
                            active_endpoint: None,
                            status: ConnectivityStatus::Connected,
                        });
                        return Some(MeshEvent::DirectConnectionUpgraded {
                            peer_id: event.remote_peer_id,
                        });
                    }
                    Err(error) => {
                        warn!(
                            peer_id = %event.remote_peer_id,
                            error = %error,
                            "Direct connection upgrade failed"
                        );
                        return Some(MeshEvent::DirectConnectionUpgradeFailed {
                            peer_id: event.remote_peer_id,
                            error: error.to_string(),
                        });
                    }
                },

                // Connection events
                SwarmEvent::ConnectionEstablished {
                    peer_id,
                    endpoint,
                    num_established,
                    ..
                } => {
                    let connection_type = if endpoint
                        .get_remote_address()
                        .to_string()
                        .contains("p2p-circuit")
                    {
                        ConnectionType::Relayed
                    } else {
                        ConnectionType::Direct
                    };

                    let num_connections = num_established.get();
                    let remote_addr = endpoint.get_remote_address().clone();
                    let is_relay_connection = self.relay_endpoint_matches(&remote_addr);

                    info!(
                        peer_id = %peer_id,
                        address = %remote_addr,
                        connection_type = ?connection_type,
                        num_established = num_connections,
                        "Connection established"
                    );
                    let _ = persist_runtime_connectivity_state(&DeviceConnectivityState {
                        active_path: match connection_type {
                            ConnectionType::Direct => ConnectivityPath::Direct,
                            ConnectionType::Relayed | ConnectionType::Unknown => {
                                ConnectivityPath::Relayed
                            }
                        },
                        active_endpoint: Some(remote_addr.to_string()),
                        status: ConnectivityStatus::Connected,
                    });

                    if is_relay_connection {
                        self.relay_peer_id = Some(peer_id);
                        return Some(MeshEvent::RelayConnected {
                            relay_peer_id: peer_id,
                            relay_addr: remote_addr,
                        });
                    }

                    return Some(MeshEvent::PeerConnected {
                        peer_id,
                        connection_info: ConnectionInfo {
                            connection_type,
                            remote_addr,
                            num_established: num_connections,
                        },
                    });
                }

                SwarmEvent::ConnectionClosed {
                    peer_id,
                    cause,
                    num_established,
                    ..
                } => {
                    let relay_closed = self.relay_peer_id == Some(peer_id);
                    if relay_closed {
                        self.relay_peer_id = None;
                    }
                    if let Some(error) = cause {
                        warn!(peer_id = %peer_id, error = ?error, remaining = num_established, "Connection closed with error");
                    } else {
                        info!(peer_id = %peer_id, remaining = num_established, "Connection closed");
                    }
                    let has_live_peers = self.swarm.connected_peers().next().is_some();
                    let _ = persist_runtime_connectivity_state(&DeviceConnectivityState {
                        active_path: if self.relay_peer_id.is_some() && !has_live_peers {
                            ConnectivityPath::Relayed
                        } else {
                            ConnectivityPath::Direct
                        },
                        active_endpoint: None,
                        status: if has_live_peers {
                            ConnectivityStatus::Connected
                        } else {
                            ConnectivityStatus::Degraded
                        },
                    });
                    if relay_closed {
                        return Some(MeshEvent::RelayDisconnected {
                            relay_peer_id: peer_id,
                        });
                    }
                    return Some(MeshEvent::PeerDisconnected { peer_id });
                }

                // Listen events
                SwarmEvent::NewListenAddr { address, .. } => {
                    info!(address = %address, "Listening on new address");
                    return Some(MeshEvent::NewListenAddr { address });
                }

                SwarmEvent::NewExternalAddrCandidate { address } => {
                    info!(address = %address, "Discovered external address candidate");
                    let _ = persist_observed_reachability_addr(&address);
                    return Some(MeshEvent::ExternalAddrCandidateDiscovered { address });
                }

                SwarmEvent::ExternalAddrConfirmed { address } => {
                    info!(address = %address, "Confirmed external address");
                    let _ = persist_observed_reachability_addr(&address);
                    return Some(MeshEvent::ExternalAddrConfirmed { address });
                }

                // Dial events
                SwarmEvent::OutgoingConnectionError { peer_id, error, .. } => {
                    if let Some(peer_id) = peer_id {
                        warn!(peer_id = %peer_id, error = %error, "Outgoing connection error");
                    } else {
                        warn!(error = %error, "Outgoing connection error");
                    }
                }

                SwarmEvent::IncomingConnectionError { error, .. } => {
                    warn!(error = %error, "Incoming connection error");
                }

                SwarmEvent::ListenerClosed { reason, .. } => {
                    if let (Some(relay_peer_id), Err(error)) = (self.relay_peer_id, reason.as_ref())
                    {
                        warn!(relay = %relay_peer_id, error = ?error, "Listener closed");
                        if error.to_string().contains("Reservation") {
                            return Some(MeshEvent::ReservationDenied { relay_peer_id });
                        }
                    }
                }

                // Other events
                event => {
                    debug!("Swarm event: {:?}", event);
                }
            }
        }
    }

    /// Get the current relay peer ID
    pub fn relay_peer_id(&self) -> Option<PeerId> {
        self.relay_peer_id
    }

    /// Get a list of connected peers
    pub fn connected_peers(&self) -> Vec<PeerId> {
        self.swarm.connected_peers().copied().collect()
    }

    /// Check if connected to a specific peer
    pub fn is_connected(&self, peer_id: &PeerId) -> bool {
        self.swarm.is_connected(peer_id)
    }

    /// Set the ring neighbors for all-reduce communication
    #[instrument(skip(self), fields(local = %self.local_peer_id(), left = %left, right = %right))]
    pub fn set_ring_neighbors(
        &mut self,
        left: PeerId,
        left_addrs: &[Multiaddr],
        left_plan: Option<&PeerPunchPlan>,
        right: PeerId,
        right_addrs: &[Multiaddr],
        right_plan: Option<&PeerPunchPlan>,
    ) {
        info!("Setting ring neighbors");

        self.ring_connections = Some(RingConnections {
            left_peer: left,
            right_peer: right,
        });

        // Direct is the canonical neighbor path.
        self.dial_neighbor(left, left_addrs, left_plan);
        self.dial_neighbor(right, right_addrs, right_plan);

        info!("Ring neighbors set: left={}, right={}", left, right);
    }

    /// Get the current ring neighbors
    pub fn get_ring_neighbors(&self) -> Option<&RingConnections> {
        self.ring_connections.as_ref()
    }

    /// Clear ring neighbors
    pub fn clear_ring_neighbors(&mut self) {
        self.ring_connections = None;
        info!("Ring neighbors cleared");
    }

    /// Get the left neighbor peer ID
    pub fn left_neighbor(&self) -> Option<PeerId> {
        self.ring_connections.as_ref().map(|r| r.left_peer)
    }

    /// Get the right neighbor peer ID
    pub fn right_neighbor(&self) -> Option<PeerId> {
        self.ring_connections.as_ref().map(|r| r.right_peer)
    }
}

fn relay_base_addr(addr: &Multiaddr) -> Vec<String> {
    addr.iter()
        .take_while(|protocol| {
            !matches!(
                protocol,
                libp2p::multiaddr::Protocol::P2p(_) | libp2p::multiaddr::Protocol::P2pCircuit
            )
        })
        .map(|protocol| protocol.to_string())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::types::{PeerPunchPlan, PunchPathReason, PunchPathStrategy};

    #[test]
    fn test_mesh_swarm_builder() {
        let keypair = libp2p::identity::Keypair::generate_ed25519();
        let swarm = MeshSwarm::builder(keypair)
            .with_keep_alive(Duration::from_secs(60))
            .build();

        assert!(swarm.is_ok(), "Swarm should build successfully");
    }

    #[test]
    fn test_default_config() {
        let config = MeshSwarmConfig::default();
        assert_eq!(config.keep_alive, Duration::from_secs(60));
        assert!(config
            .relay_addr
            .to_string()
            .contains("relay.meshnet.invalid"));
    }

    #[test]
    fn test_mesh_swarm_peer_id() {
        let keypair = libp2p::identity::Keypair::generate_ed25519();
        let expected_peer_id = keypair.public().to_peer_id();
        let swarm = MeshSwarm::builder(keypair).build().unwrap();

        assert_eq!(swarm.local_peer_id(), &expected_peer_id);
    }

    #[test]
    fn test_builder_with_custom_relay() {
        let keypair = libp2p::identity::Keypair::generate_ed25519();
        let custom_relay: Multiaddr = "/ip4/192.168.1.1/tcp/5000".parse().unwrap();

        let swarm = MeshSwarm::builder(keypair)
            .with_relay_addr(custom_relay.clone())
            .build()
            .unwrap();

        assert_eq!(swarm.config.relay_addr, custom_relay);
    }

    #[test]
    fn test_connected_peers_empty() {
        let keypair = libp2p::identity::Keypair::generate_ed25519();
        let swarm = MeshSwarm::builder(keypair).build().unwrap();

        assert_eq!(swarm.connected_peers().len(), 0);
    }

    #[tokio::test]
    async fn test_set_ring_neighbors_emits_punch_attempts_for_both_neighbors() {
        let keypair = libp2p::identity::Keypair::generate_ed25519();
        let mut swarm = MeshSwarm::builder(keypair).build().unwrap();
        let left = PeerId::random();
        let right = PeerId::random();

        let left_plan = PeerPunchPlan {
            source_device_id: "self".to_string(),
            target_device_id: "left".to_string(),
            target_peer_id: left.to_string(),
            strategy: PunchPathStrategy::SimultaneousDial,
            reason: PunchPathReason::RelayPath,
            relay_rendezvous_required: true,
            attempt_window_ms: 5_000,
            issued_at_ms: 1_700_000_000_000,
            target_candidates: vec![crate::connectivity::DirectPeerCandidate {
                endpoint: "/ip4/127.0.0.1/tcp/4101".to_string(),
                transport: crate::connectivity::DirectCandidateTransport::Tcp,
                scope: crate::connectivity::DirectCandidateScope::Private,
                source: crate::connectivity::DirectCandidateSource::LocalListen,
                priority: 21,
                last_updated_ms: 1_700_000_000_000,
            }],
        };
        let right_plan = PeerPunchPlan {
            source_device_id: "self".to_string(),
            target_device_id: "right".to_string(),
            target_peer_id: right.to_string(),
            strategy: PunchPathStrategy::SimultaneousDial,
            reason: PunchPathReason::PrivateReachabilityOnly,
            relay_rendezvous_required: false,
            attempt_window_ms: 5_000,
            issued_at_ms: 1_700_000_000_000,
            target_candidates: vec![crate::connectivity::DirectPeerCandidate {
                endpoint: "/ip4/127.0.0.1/tcp/4102".to_string(),
                transport: crate::connectivity::DirectCandidateTransport::Tcp,
                scope: crate::connectivity::DirectCandidateScope::Private,
                source: crate::connectivity::DirectCandidateSource::LocalListen,
                priority: 21,
                last_updated_ms: 1_700_000_000_000,
            }],
        };

        swarm.set_ring_neighbors(left, &[], Some(&left_plan), right, &[], Some(&right_plan));

        assert_eq!(swarm.left_neighbor(), Some(left));
        assert_eq!(swarm.right_neighbor(), Some(right));

        let punch_events = swarm
            .pending_events
            .iter()
            .filter(|event| matches!(event, MeshEvent::PunchPathAttemptInitiated { .. }))
            .count();
        let queued_punch_events = swarm
            .pending_events
            .iter()
            .filter(|event| matches!(event, MeshEvent::PunchPathAttemptInitiated { .. }))
            .count();

        assert_eq!(punch_events, 2);
        assert_eq!(queued_punch_events, 2);
    }
}
