-- Create ledger_events table
-- Immutable append-only log of all credit-related events
CREATE TABLE ledger_events (
    event_id TEXT PRIMARY KEY,  -- UUID generated by application
    network_id TEXT NOT NULL REFERENCES networks(network_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,  -- 'job_started', 'job_completed', 'credits_burned', 'credits_earned'
    job_id TEXT,  -- UUID of the job (optional for non-job events)
    device_id TEXT REFERENCES devices(device_id) ON DELETE SET NULL,
    user_id TEXT,  -- User who triggered the event (optional)
    credits_amount REAL,  -- Credit delta (positive for earning, negative for burning)
    metadata TEXT,  -- JSON metadata (job details, etc.)
    timestamp TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Indexes for common ledger queries
CREATE INDEX idx_ledger_network_time ON ledger_events(network_id, timestamp DESC);
CREATE INDEX idx_ledger_device_time ON ledger_events(device_id, timestamp DESC);
CREATE INDEX idx_ledger_job ON ledger_events(job_id);
CREATE INDEX idx_ledger_type ON ledger_events(event_type);
